#!/usr/bin/env bash
set -euo pipefail

workspace="$(mktemp -d)"
cleanup() { rm -rf "$workspace"; }
trap cleanup EXIT

cd "$workspace"
cat > .envrc <<'ENVRC'
export PI_DIRENV_BASH_TEST_VALUE="loaded-from-direnv"
ENVRC

if ! command -v direnv >/dev/null 2>&1; then
  echo "SKIP: direnv is not installed" >&2
  exit 0
fi

direnv allow . >/dev/null

# This is the same shell pattern generated by extensions/direnv-bash/direnv.ts.
# It must run in the same shell process as the command that needs the env.
if command -v direnv >/dev/null 2>&1; then
  __pi_direnv_export="$(direnv export bash)"
  __pi_direnv_status=$?
  if [ $__pi_direnv_status -eq 0 ]; then
    eval "$__pi_direnv_export"
  else
    :
  fi
  unset __pi_direnv_export __pi_direnv_status
else
  :
fi

actual="${PI_DIRENV_BASH_TEST_VALUE:-missing}"
if [ "$actual" != "loaded-from-direnv" ]; then
  echo "FAIL: expected loaded-from-direnv, got '$actual'" >&2
  exit 1
fi

echo "PASS: direnv export bash loaded PI_DIRENV_BASH_TEST_VALUE=$actual"
